version: "3"
services:
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:5.0.12
  blog:
    image: blog:latest
    build: .
    ports:
      - 9090:9090
    depends_on:
      - mysql
      - redis