# 公共配置

server:
  servlet:
    context-path: /

spring:
  application:
    name: blog-springboot
  # 配置运行环境：dev|test|prod 等等，开发阶段使用dev环境，上线时通过启动参数切换到prod环境
  profiles:
    active: dev

# Mybatis配置
mybatis:
  #配置Mapper映射文件
  mapper-locations: classpath:mapper/*Mapper.xml